[package]
name = "rsredlock"
version = "0.1.0"
authors = ["svahil9911 <vishalchauhan9911@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.19.0"
lazy_static = "1.4.0"
